/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-02-12 15:46:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class post_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html><head><title>Post Order</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://www.w3schools.com/lib/w3.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"w3.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        <style>\n");
      out.write("          \n");
      out.write("            body,div,ul,li,p{\n");
      out.write("                font-family:arial;\n");
      out.write("\n");
      out.write("            }\n");
      out.write("            #header{\n");
      out.write("                background-color:#FFA500;\n");
      out.write("                \n");
      out.write("          color:white;\n");
      out.write("        font-size: 36px;\n");
      out.write("        font-family: Arial, sans-serif;\n");
      out.write("        text-align: center;\n");
      out.write("        padding: 20px;\n");
      out.write("        \n");
      out.write("        border-bottom: 2px solid white;\n");
      out.write("        box-shadow: 0px 5px 10px #888888;\n");
      out.write("            }\n");
      out.write("            #header .logo a{\n");
      out.write("                padding-left:40px;\n");
      out.write("                color:black;\n");
      out.write("                text-decoration:underline;\n");
      out.write("                font-size:50px;\n");
      out.write("                font-family : Trirong,serif;\n");
      out.write("                font-size:60px;\n");
      out.write("                text-shadow:3px 3px 3px #FF0000\"\n");
      out.write("            }\n");
      out.write("            /** Navigation **/\n");
      out.write("            #navigation {\n");
      out.write("                display: inline-block;\n");
      out.write("                list-style: none;\n");
      out.write("                line-height: 50px;\n");
      out.write("                margin: 0;\n");
      out.write("                padding-left: 20;\n");
      out.write("            }\n");
      out.write("            #navigation ul {\n");
      out.write("                display: inline-block;\n");
      out.write("                list-style: none;\n");
      out.write("                margin: 0;\n");
      out.write("                padding: 0;\n");
      out.write("            }\n");
      out.write("            #navigation li {\n");
      out.write("                float: left;\n");
      out.write("                width: 180px;\n");
      out.write("                text-align: right;\n");
      out.write("            }\n");
      out.write("            #navigation li a {\n");
      out.write("                color: #616161;\n");
      out.write("                font-size: 20px;\n");
      out.write("                line-height: 10px;\n");
      out.write("                text-decoration: none;\n");
      out.write("            }\n");
      out.write("            #navigation li a:hover {\n");
      out.write("                font-size: 20px;\n");
      out.write("                color: #212121;\n");
      out.write("\n");
      out.write("            }\n");
      out.write("            #navigation li.active a {\n");
      out.write("                color: black;\n");
      out.write("                padding:12px;\n");
      out.write("                background-color:transparent;\n");
      out.write("                font-size:20px;\n");
      out.write("                border: 2px solid black;\n");
      out.write("                border-radius:10px;\n");
      out.write("            }\n");
      out.write("            #wish{\n");
      out.write("                padding:10px;\n");
      out.write("                font-size:30px;\n");
      out.write("            }\n");
      out.write("            input[type=\"checkbox\"], input[type=\"radio\"] {\n");
      out.write("                width: 30px;\n");
      out.write("                height: 30px;\n");
      out.write("                border-width: 0;\n");
      out.write("                transition: all .3s linear;\n");
      out.write("            }\n");
      out.write("            img{\n");
      out.write("            border-radius:50px;\n");
      out.write("            }\n");
      out.write("        \n");
      out.write("        </style>\n");
      out.write("        <div id=\"header\">\n");
      out.write("            <div>\n");
      out.write("                <div class=\"logo\">\n");
      out.write("                    <a href=\"index.jsp\">Pizza<img src=\"Images\\logo-pizza-villa-logo.jpg\" width=\"100\" height=\"100\" > Villa</a>\n");
      out.write("                </div>\n");
      out.write("                <div id=\"span\">\n");
      out.write("                    <ul id=\"navigation\">\n");
      out.write("                         <li>\n");
      out.write("                          <a href=\"success.jsp\">HOME</a>\n");
      out.write("                    </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"StoreLocator.jsp\">Store Locator</a>\n");
      out.write("                        </li>\n");
      out.write("                       \n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"AboutUs.jsp\">About us</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\">Contact us</a>\n");
      out.write("                        </li>\n");
      out.write("                         <li>\n");
      out.write("                            <a href=\"logout.jsp\">Log out <i>(");
out.print(session.getAttribute("userid")); 
      out.write(")</i></a>	\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <fieldset>\n");
      out.write("            <legend> Enter Your Delivery Address:</legend>\n");
      out.write("            <table border=0>\n");
      out.write("                <form method=\"post\"  action = \"thank.jsp\" class=\"w3-container\">\n");
      out.write("                    <tr><th>Enter full Name :</td><td><input class=\"w3-input\"  type=\"text\" name=\"fname\" id=\"fname\" required></td></tr>\n");
      out.write("                    <tr><th>Enter Mobile Num. :</td><td><input class=\"w3-input\"  typr=\"number\" name=\"mobile\" id=\"mnum\" required></td></tr>\n");
      out.write("                    <tr><th>Enter Email Address :</td><td><input class=\"w3-input\"  type=\"email\" name=\"email\" id=\"ename\"></td></tr>\n");
      out.write("                    <tr><th>Select your City</th><td><select name=\"city\">\n");
      out.write("                                <option value=\"1\" selected>---choose city---</option>\n");
      out.write("                                <option value=\"Mumbai\">Mumbai</option>\n");
      out.write("                                <option value=\"pune\">Pune</option>\n");
      out.write("                                <option value=\"nasik\">Nashik</option>\n");
      out.write("                                <option value=\"shirdi\">Shirdi</option>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                            </select></td></tr>\n");
      out.write("                    <tr><th>Choose delivery region:</th><td><select name=\"cars\">\n");
      out.write("                                <option value=\"1\" selected>---choose region---</option>\n");
      out.write("                                <option value=\"shirish\">Amrutnagar</option>\n");
      out.write("                                <option value=\"rohan\">Sangamner Bazar Peth</option>\n");
      out.write("                                <option value=\"shubham\">Grant Road Mumbai</option>\n");
      out.write("                                <option value=\"prasad\">Wagholi,Pune</option> \n");
      out.write("                                <option value=\"amit\">Pune Bypass, Samnapur Area</option>  \n");
      out.write("\n");
      out.write("                            </select>	</td></tr>\n");
      out.write("                    <tr><th>Enter full Address :</th><td><input class=\"w3-input\"  type=\"text\" id=\"address\" name=\"address\" /></td></tr>\n");
      out.write("                    <br>\n");
      out.write("                    <br>\n");
      out.write("                    <tr><th colspan=2>  <input class='w3-xlarge w3-btn w3-block w3-black' type=\"submit\"  value=\"Place Order\"/> </th></tr>						  \n");
      out.write("                </form>\n");
      out.write("            </table></fieldset>\n");
      out.write("        <div id=\"footer\" style=\"height:270px; background-color:#f5f5f5;display:block;\">\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
