/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-02-12 14:42:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class StoreLocator_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("  <title>Pizza Villa - Store Locator </title>\r\n");
      out.write("   <meta name=\"description\" content=\"Pizza Villa - Store Locator \">\r\n");
      out.write("   	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://1441pizzeria.com/assets/wla_new/css/bootstrap.min.css\" media=\"all\" />\r\n");
      out.write("   	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://1441pizzeria.com/assets/wla_new/css/line-awesome.min.css\" media=\"all\" />\r\n");
      out.write("	   	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CYanone+Kaffeesatz:200,300,400,700\" >\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://1441pizzeria.com/assets/wla_new/css/style_wla_20221007_4.css\" media=\"all\" />\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.4/css/intlTelInput.css\" integrity=\"sha256-rTKxJIIHupH7lFo30458ner8uoSSRYciA0gttCkw1JE=\" crossorigin=\"anonymous\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("   <body>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       <style>\r\n");
      out.write("            body,div,ul,li,p{\r\n");
      out.write("                font-family:arial;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("            #header{\r\n");
      out.write("                background-color:#FFA500;\r\n");
      out.write("                \r\n");
      out.write("          color:white;\r\n");
      out.write("        font-size: 36px;\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        \r\n");
      out.write("        border-bottom: 2px solid white;\r\n");
      out.write("        box-shadow: 0px 5px 10px #888888;\r\n");
      out.write("            }\r\n");
      out.write("            #header .logo a{\r\n");
      out.write("                padding-left:40px;\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("                color:black;\r\n");
      out.write("                text-decoration:underline;\r\n");
      out.write("                font-size:50px;\r\n");
      out.write("                font-family : Trirong,serif;\r\n");
      out.write("                font-size:60px;\r\n");
      out.write("                text-shadow:3px 3px 3px #FF0000\"\r\n");
      out.write("            }\r\n");
      out.write("            /** Navigation **/\r\n");
      out.write("            #navigation {\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                list-style: none;\r\n");
      out.write("                line-height: 50px;\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                padding-left: 20px;\r\n");
      out.write("                padding-bottom:10px;\r\n");
      out.write("            }\r\n");
      out.write("            #navigation ul {\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                list-style: none;\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                padding: 0;\r\n");
      out.write("            }\r\n");
      out.write("            #navigation li {\r\n");
      out.write("                float: left;\r\n");
      out.write("                width: 180px;\r\n");
      out.write("                text-align: right;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("            #navigation li a {\r\n");
      out.write("                color: #616161;\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("                line-height: 10px;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("            }\r\n");
      out.write("            #navigation li a:hover {\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("                color: #212121;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("            #navigation li.active a {\r\n");
      out.write("                color: black;\r\n");
      out.write("                padding:10px;\r\n");
      out.write("                background-color:transparent;\r\n");
      out.write("                font-size:20px;\r\n");
      out.write("                border: 2px solid black;\r\n");
      out.write("                border-radius:10px;\r\n");
      out.write("            }\r\n");
      out.write("            #wish{\r\n");
      out.write("                padding:10px;\r\n");
      out.write("                font-size:30px;\r\n");
      out.write("            }\r\n");
      out.write("            input[type=\"checkbox\"], input[type=\"radio\"] {\r\n");
      out.write("                width: 30px;\r\n");
      out.write("                height: 30px;\r\n");
      out.write("                border-width: 0;\r\n");
      out.write("                transition: all .3s linear;\r\n");
      out.write("            }\r\n");
      out.write("            img{\r\n");
      out.write("            border-radius:50px;\r\n");
      out.write("           \r\n");
      out.write("            \r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("        </style> \r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"logo\">\r\n");
      out.write("                <a href =\"#\"></a><img src=\"Images\\logo-pizza-villa-logo.jpg\" width=\"100\" height=\"100\"  align=\"right\" > </a>\r\n");
      out.write("                 <a href=\"#\">Pizza Villa</a> \r\n");
      out.write("                   \r\n");
      out.write("                    <!-- <span id=\"wish\"><img src=\"Images/shopping-cart.png\" height=40 width=40> </span>\r\n");
      out.write(" -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"span\">\r\n");
      out.write("                    <ul id=\"navigation\">\r\n");
      out.write("                        <li >\r\n");
      out.write("                            <a href=\"success.jsp\">Welcome</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"active\">\r\n");
      out.write("                            <a href=\"#\">Store Locator</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"feedback.jsp\">Contact Us</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"AboutUs.jsp\">About us</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"logout.jsp\">Log out <i>(");
out.print(session.getAttribute("userid")); 
      out.write(")</i></a>	\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      <style>\r\n");
      out.write("         .spinner {\r\n");
      out.write("            display: block;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            z-index: 1031;\r\n");
      out.write("            /* High z-index so it is on top of the page */\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            right: 50%;\r\n");
      out.write("            /* or: left: 50%; */\r\n");
      out.write("            margin-top: -..px;\r\n");
      out.write("            /* half of the elements height */\r\n");
      out.write("            margin-right: -..px;\r\n");
      out.write("            /* half of the elements widht */\r\n");
      out.write("            color: var(--main-bg-color) !important;\r\n");
      out.write("            width: 4em;\r\n");
      out.write("            height: 4em;\r\n");
      out.write("         }\r\n");
      out.write("         .iti {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("         }\r\n");
      out.write("         .iti .form-control {\r\n");
      out.write("            padding-left: 45px !important;\r\n");
      out.write("         }\r\n");
      out.write("         .iti__arrow{\r\n");
      out.write("            display:none;\r\n");
      out.write("         }\r\n");
      out.write("         .iti--separate-dial-code .iti__selected-flag > .iti__flag {\r\n");
      out.write("            display: none;\r\n");
      out.write("         }\r\n");
      out.write("         .iti--separate-dial-code .iti__selected-dial-code {\r\n");
      out.write("            margin-left: 0px;\r\n");
      out.write("         }\r\n");
      out.write("         .iti__selected-flag{\r\n");
      out.write("            padding:0 8px 0 8px;\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("      </style>\r\n");
      out.write("\r\n");
      out.write("      <style>\r\n");
      out.write("         @media ( min-width: 767px){\r\n");
      out.write("            #site-navigation .navbar-collapse .nav-link{\r\n");
      out.write("               background:#009948!important; \r\n");
      out.write("               color: #ffffff !Important\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         @media (max-width: 767px){\r\n");
      out.write("            #site-navigation .navbar-collapse .nav-link{\r\n");
      out.write("               background: #fff !important;\r\n");
      out.write("               color: #000 !important;\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("\r\n");
      out.write("      </style>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("<div class=\"store-page-wrapper\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-xl-8 col-12 text-center text-xl-left\">\r\n");
      out.write("		<div class=\"sections-content\">\r\n");
      out.write("						 <h1><span class=\"font-weight-light\">15 Pizza Outlets Near You</span></h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"w-100 mt-xl-4 mt-3\"></div>\r\n");
      out.write("            <div class=\"col-xl-4 col-12 order-2 order-xl-0 mt-4 mt-xl-0\">\r\n");
      out.write("                <div class=\"card store-left-panel\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        Popular Cities\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <ul class=\"list-unstyled store-city-list\">\r\n");
      out.write("                                                            <li>\r\n");
      out.write("                                  \r\n");
      out.write("                                        <i class=\"la la-map-marker\"></i>Mumbai                                    \r\n");
      out.write("                                </li>\r\n");
      out.write("                                                            <li>\r\n");
      out.write("                                    \r\n");
      out.write("                                        <i class=\"la la-map-marker\"></i>Navi Mumbai                                 \r\n");
      out.write("                                </li>\r\n");
      out.write("                                                            <li>\r\n");
      out.write("                                  \r\n");
      out.write("                                        <i class=\"la la-map-marker\"></i>Pune                                   \r\n");
      out.write("                                </li>\r\n");
      out.write("                                                            <li>\r\n");
      out.write("                                    \r\n");
      out.write("                                        <i class=\"la la-map-marker\"></i>Surat                                   \r\n");
      out.write("                                </li>\r\n");
      out.write("                            \r\n");
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl-8 col-12 px-xl-4\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"card-wrap\">\r\n");
      out.write("		                        <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Vile Parle,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Vile Parle,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">SHOP 9-10, Tirupati Apartment, Plot no 288, Nehru Rd, Vile Parle East,  Mumbai, Maharashtra 400057</p>\r\n");
      out.write("                                                                       \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Juhu,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Juhu,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Shop No. 1, Plot No 9. Nirav Apartment, Gulmohar Road No. 1, Vile Parle West, Mumbai - 400049</p>\r\n");
      out.write("                                                                        \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Malad,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Malad,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Shop No. 11, Raj Infinia, Evershine Nagar, Near Movie Time Cinema, Malad West, Mumbai, Maharashtra 400064</p>\r\n");
      out.write("                                                                       \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Kandivali,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Kandivali,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Ground floor, Shop No.1,2,3,4, Swapnapurti, Opp. Trillium Tower, Thakur Village, Kandivali East, Greater Mumbai Ward-R/S, Greater Mumbai, Maharashtra 400101</p>\r\n");
      out.write("                                                                        \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Mira Road,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Mira Road,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">B2/B3, Ground Floor, Dev Paradise, Kanakia Road, Near Star Bazaar, Mira Road, Mira Bhayandar, Maharashtra 401107</p>\r\n");
      out.write("                                                                      \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Vesu,Surat\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Vesu,Surat</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Pizza Villa Surat, F/1,2,3,4,5 Aagam vivianna, opp. Florence Residency, Vesu, Surat, Gujarat 395007</p>\r\n");
      out.write("                                                                        \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Kamala Mills,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Kamala Mills,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Trade World B, Kamala Mills Compound, Senapati Bapat Road, Lower Parel, Mumbai, Maharashtra 400013</p>\r\n");
      out.write("                                                                       \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Kala Ghoda, Fort,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Kala Ghoda, Fort,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">First Floor, Kalaghoda Building Bhadekaru Co-operative CHSL, 30, K Dubash Marg, Kala Ghoda, Fort, Mumbai, Maharashtra 400001</p>\r\n");
      out.write("                                                                     \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Lokhandwala,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Lokhandwala,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Ground Floor, Shop no. 21, Oshiwara Link Plaza, Near Oshiwara Police  Station, Link Road, Jogeshwari West, Mumbai, Maharashtra 400102</p>\r\n");
      out.write("                                                                      \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Thane,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Thane,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Shop No. 5, Ashar Tiara Commercial Complex, Pokharan Rd Number 2, opp. TMC Water Tank, Vasant Vihar, Thane West, Mumbai, Maharashtra 400610</p>\r\n");
      out.write("                                                                      \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Bandra,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Bandra,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Shop no. 5, Silver Pearl building, off waterfield road,  Bandra West, Mumbai, Maharashtra 400050</p>\r\n");
      out.write("                                                                        \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Kemps Corner,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Kemps Corner,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Khatau Mansion, Oomer Park, Unit No: 50, Hussain Manor, 95 F, Warden Rd, Mumbai, Maharashtra 400036</p>\r\n");
      out.write("                                                                         \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Bhandup,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Bhandup,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">P N Kothari Industrial Estate, Lal Bahadur Shastri Rd, Bhandup, Mumbai, 400078</p>\r\n");
      out.write("                                         \r\n");
      out.write("                                                                         \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Powai,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Powai,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Shop - 41, Prathamesh Galaxy Opp. Vijay Vihar Building, Powai, Mumbai, Maharashtra 400076</p>\r\n");
      out.write("                                                                        \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Sion,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Sion,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Shop No. 5, Plot No. 263, Shri Noattom Niwas Co. Hsg. Soc. Ltd., Sion Main Road, Sion, Mumbai - 400022</p>\r\n");
      out.write("                                                                          \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Seawood,Navi Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Seawood,Navi Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Shop No.3, Nageshwar Dham, Sector 44A, Krishna Changa Marg, Next to Kotak Bank, Seawood, Navi Mumbai - 400706</p>\r\n");
      out.write("                                                                         \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Vashi,Navi Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Vashi,Navi Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Unit no. 45 & 46,Plot no. 47,Shivam Complex Sector - 19E, Vashi, Navi Mumbai - 400 705</p>\r\n");
      out.write("                                                                         \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Kothrud,Pune\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Kothrud,Pune</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Mantri Park, C-18, near Natraj Gas, behind Kothrud Bus Stand Rd, Tejas Society, Dahanukar Colony, Kothrud, Pune, Maharashtra 411038</p>\r\n");
      out.write("                                                                         \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Balewadi,Pune\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Balewadi,Pune</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Shop No.2, Ground Floor, Elite Premio, Balewadi, Haveli, Pune, Maharashtra, 411045</p>\r\n");
      out.write("                                                                        \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Koregaon Park,Pune\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Koregaon Park,Pune</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">5, Galaxy Garden, N Main Rd, Vasani Nagar, Koregaon Park, Pune, Maharashtra 411001</p>\r\n");
      out.write("                                                                       \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div  class=\"store-wrap\">\r\n");
      out.write("                            <div class=\"media\">\r\n");
      out.write("				<img class=\"mr-xl-3\" src=\"Images/logo-pizza-villa-logo.jpg\" alt=\"Pizza Villa- Chembur,Mumbai\" width=\"200px\" height=\"200px\">\r\n");
      out.write("                                <div class=\"media-body\">\r\n");
      out.write("                                                                             <h2 class=\"mt-0\">Pizza Villa</h2>\r\n");
      out.write("                                         <ul style=\"color:#000\">\r\n");
      out.write("                                             <li><i class=\"la la-map-marker\"></i> Chembur,Mumbai</li>\r\n");
      out.write("                                             <li><i class=\"la la-clock\"></i> 30 mins Delivery Time</li>\r\n");
      out.write("                                         </ul>\r\n");
      out.write("                                         <p class=\"mt-2\">Shop No. 8, Ground Floor, Chhadva Apartments,, Sion  Trombay Road, Borla, Union Park, Chembur, Mumbai,  Maharashtra, Mumbai, Maharashtra 400071</p>\r\n");
      out.write("                                                                       \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                </div>    \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("               \r\n");
      out.write("                </div>\r\n");
      out.write("        \r\n");
      out.write("<div>\r\n");
      out.write("			       <i class='las la-map-pin'></i> Madhu Industrial Estate, A-2, Pandurang Budhkar Marg, Lower Parel, Mumbai, Maharashtra 400013\r\n");
      out.write("                     <a href=\"mailto:prathamesh2582@gmail.com\"> prathamesh2582@gmail.com </a>\r\n");
      out.write("                               <a href=\"tel:+91 9594931244\"> +91 9594931244</a>\r\n");
      out.write("                   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </body>\r\n");
      out.write("\r\n");
      out.write(" </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
