/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-02-10 05:48:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Demo.MinPath;

public final class success_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Demo.MinPath");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    if ((session.getAttribute("userid") == null) || (session.getAttribute("userid") == "")) {


      out.write("\n");
      out.write("<center>\n");
      out.write("    <p align=\"center\" style=\"font-size:45px\">Pizza Villa</p>\n");
      out.write("    Session expired.\n");
      out.write("    <a href=\"index.jsp\" style=\"color:#ff5500;padding-top:23px\">Sign in here</a>\n");
      out.write("</center>\n");
} else {


      out.write("\n");
      out.write("<html>\n");
      out.write("    <head><title>Pizza Villa </title>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css1.css\" type=\"text/css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"w3.css\" type=\"text/css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"../CSS/header.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("        <script>\n");
      out.write("            var b = 0;\n");
      out.write("            function update_value(chk_bx) {\n");
      out.write("                if (chk_bx.checked)\n");
      out.write("                {\n");
      out.write("                    var a = \"checked\";\n");
      out.write("                    b += 1;\n");
      out.write("                } else {\n");
      out.write("                    var a = \"not checked\";\n");
      out.write("                    if (b > 0) {\n");
      out.write("                        b -= 1;\n");
      out.write("                    } else if (b == 0) {\n");
      out.write("                        b = 0;\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("                if (b == 0)\n");
      out.write("                {\n");
      out.write("                    document.getElementById('wish').innerHTML = '<img src=\"Images/shopping-cart.png\" height=40 width=40>&nbsp&nbsp0';\n");
      out.write("\n");
      out.write("                } else {\n");
      out.write("                    document.getElementById('wish').innerHTML = '<img src=\"Images/shopping-cart.png\" height=40 width=40>&nbsp&nbsp' + b + '';\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      Demo.MinPath test = null;
      test = (Demo.MinPath) _jspx_page_context.getAttribute("test", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (test == null){
        test = new Demo.MinPath();
        _jspx_page_context.setAttribute("test", test, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\n");
      out.write("       <style>\n");
      out.write("            body,div,ul,li,p{\n");
      out.write("                font-family:arial;\n");
      out.write("\n");
      out.write("            }\n");
      out.write("           #header{\n");
      out.write("                background-color:#FFA500;\n");
      out.write("                \n");
      out.write("          color:white;\n");
      out.write("        font-size: 36px;\n");
      out.write("        font-family: Arial, sans-serif;\n");
      out.write("        text-align: center;\n");
      out.write("        padding: 10px;\n");
      out.write("        \n");
      out.write("        border-bottom: 2px solid white;\n");
      out.write("        box-shadow: 0px 5px 10px #888888;\n");
      out.write("            }\n");
      out.write("            #header .logo a{\n");
      out.write("                padding-left:450px;\n");
      out.write("                color:black;\n");
      out.write("                text-decoration:underline;\n");
      out.write("                font-size:50px;\n");
      out.write("                font-family : Trirong,serif;\n");
      out.write("                font-size:60px;\n");
      out.write("                text-shadow:3px 3px 3px #FF0000\"\n");
      out.write("            }\n");
      out.write("            /** Navigation **/\n");
      out.write("            #navigation {\n");
      out.write("                display: inline-block;\n");
      out.write("                list-style: none;\n");
      out.write("                line-height: 50px;\n");
      out.write("                margin: 0;\n");
      out.write("                padding-left: 20;\n");
      out.write("            }\n");
      out.write("            #navigation ul {\n");
      out.write("                display: inline-block;\n");
      out.write("                list-style: none;\n");
      out.write("                margin: 0;\n");
      out.write("                padding: 0;\n");
      out.write("            }\n");
      out.write("            #navigation li {\n");
      out.write("                float: left;\n");
      out.write("                width: 180px;\n");
      out.write("                text-align: right;\n");
      out.write("            }\n");
      out.write("            #navigation li a {\n");
      out.write("                color: #616161;\n");
      out.write("                font-size: 20px;\n");
      out.write("                line-height: 10px;\n");
      out.write("                text-decoration: none;\n");
      out.write("            }\n");
      out.write("            #navigation li a:hover {\n");
      out.write("                font-size: 20px;\n");
      out.write("                color: #212121;\n");
      out.write("\n");
      out.write("            }\n");
      out.write("            #navigation li.active a {\n");
      out.write("                color: black;\n");
      out.write("                padding:12px;\n");
      out.write("                background-color:transparent;\n");
      out.write("                font-size:20px;\n");
      out.write("                border: 2px solid black;\n");
      out.write("                border-radius:10px;\n");
      out.write("            }\n");
      out.write("            #wish{\n");
      out.write("                padding:10px;\n");
      out.write("                font-size:30px;\n");
      out.write("            }\n");
      out.write("            input[type=\"checkbox\"], input[type=\"radio\"] {\n");
      out.write("                width: 30px;\n");
      out.write("                height: 30px;\n");
      out.write("                border-width: 0;\n");
      out.write("                transition: all .3s linear;\n");
      out.write("            }\n");
      out.write("            img{\n");
      out.write("            border-radius: 50%;\n");
      out.write("            \n");
      out.write("            }\n");
      out.write("        </style> \n");
      out.write("        <div id=\"header\">\n");
      out.write("            <div>\n");
      out.write("                <div class=\"logo\">\n");
      out.write("                    <a href=\"index.html\">Pizza<img src=\"Images\\logo-pizza-villa-logo.jpg\" width=\"100\" height=\"100\" > Villa</a>\n");
      out.write("                    &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp\n");
      out.write("                    <span id=\"wish\"><img src=\"Images/shopping-cart.png\" height=40 width=40> 0</span>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <div id=\"span\">\n");
      out.write("                    <ul id=\"navigation\">\n");
      out.write("                        <li class=\"active\">\n");
      out.write("                            <a href=\"#\">Welcome</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"StoreLocator.jsp\">Store Locator</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"feedback.jsp\">Contact Us</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"AboutUs.jsp\">About us</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"logout.jsp\">Log out <i>(");
out.print(session.getAttribute("userid")); 
      out.write(")</i></a>	\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("       <form method=\"post\" action=\"order.jsp\">\n");
      out.write("      \n");
      out.write("            <table class=\"w3-table\" style=\"background-color:#F5f55\"> \n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td><img src=\"Images/pizzas/bigmess.png\" height=240 width=290></td>\n");
      out.write("                    <td><img src=\"Images/pizzas/proscuito.png\" height=240 width=290></td>\n");
      out.write("                    <td><img src=\"Images/pizzas/ml.png\" height=240 width=290></td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td><input class=\"mv1\" type=\"checkbox\" name=\"chk1\" value=\"1\" onchange=\"update_value(this);\"></td>\n");
      out.write("                    <td><input class=\"mv2\" type=\"checkbox\" name=\"chk1\" value=\"2\" onchange=\"update_value(this);\"></td>\n");
      out.write("                    <td><input class=\"mv3\" type=\"checkbox\" name=\"chk1\" value=\"3\" onchange=\"update_value(this);\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr><td align=\"center\">Veg Pizza RS.200</td><td align=\"center\">Veg Pascuito RS.270</td><td align=\"center\">Non Veg Pascuito RS. 350</td></tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td><img src=\"Images/pizzas/break.png\" height=240 width=290></td>\n");
      out.write("                    <td><img src=\"Images/pizzas/bureger.png\" height=240 width=290></td>\n");
      out.write("                    <td><img src=\"Images/pizzas/cone.png\" height=240 width=290></td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td><input class=\"mv4\" type=\"checkbox\" name=\"chk1\" value=\"4\" onchange=\"update_value(this);\"></td>\n");
      out.write("                    <td><input class=\"mv5\" type=\"checkbox\" name=\"chk1\" value=\"5\" onchange=\"update_value(this);\"></td>\n");
      out.write("                    <td><input class=\"mv6\" type=\"checkbox\" name=\"chk1\" value=\"6\" onchange=\"update_value(this);\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr><td align=\"center\">Break Pizza RS. 200</td><td align=\"center\">Burger Pizza RS. 230</td><td align=\"center\">Cone Pizza RS. 250</td></tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td><img src=\"Images/pizzas/eggs.png\" height=240 width=290></td>\n");
      out.write("                    <td><img src=\"Images/pizzas/love.png\" height=240 width=290></td>\n");
      out.write("                    <td><img src=\"Images/pizzas/rucola.png\" height=240 width=290></td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td><input class=\"mv7\" type=\"checkbox\" name=\"chk1\" value=\"7\" onchange=\"update_value(this);\"></td>\n");
      out.write("                    <td><input class=\"mv8\" type=\"checkbox\" name=\"chk1\" value=\"8\" onchange=\"update_value(this);\"></td>\n");
      out.write("                         <td><input class=\"mv9\" type=\"checkbox\" name=\"chk1\" value=\"9\" onchange=\"update_value(this);\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr><td align=\"center\">Eggs Pizza RS. 360</td><td align=\"center\">Lovely Pizza RS. 250</td><td align=\"center\">Mozz. Pizza RS.190</td></tr>\n");
      out.write("\n");
      out.write("            </table>\n");
      out.write("            <br>\n");
      out.write("            <div id=\"order\"><input type=\"submit\" style=\"font-size:45px;\" value=\"Add to cart\" class=\"w3-btn-block w3-black\" /></div>\n");
      out.write("\n");
      out.write("        </form>\n");
      out.write("        <div id=\"footer\" style=\"display:block;background-color:#f5f5f5;color:#212121;padding-bottom:70px;\">\n");
      out.write("            &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp Pizza Villa &copy Sangamner\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
